// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    double bigger05Times=0.0;
		double lessEqual05Times=0.0;
		int N= Integer.parseInt(args [0]);
		double ranNum = 0;
		double ratio = 0.0;
		for (int i=0; i<N; i++) {
			ranNum= Math.random();
			if (ranNum>0.5) {
				bigger05Times++;
			}
			else {
				lessEqual05Times++;
			}
		}
		if (lessEqual05Times==0) {
			System.out.println("> 0.5:  " + (int) bigger05Times + " times");
			System.out.println("<= 0.5: 0 times");
		}
		else {
			ratio = bigger05Times/lessEqual05Times;
			System.out.println("> 0.5:  " + (int) bigger05Times + " times");
			System.out.println("<= 0.5: " + (int) lessEqual05Times + " times");
			System.out.println("Ratio:  " + ratio);
		}
	}
}
